### ISSUE TITLE
Cannot see icon image

### ISSUE THREAD

**Issue by ChoiysApple** [tmmoond8/noticon#66]
Cannot see icon img 
<img width="1680" alt="스크린샷 2019-11-17 오전 3 34 51" src="https://user-images.githubusercontent.com/43776784/68997685-7e26d680-08ec-11ea-903c-03b0e132b2f3.png">

But I can see icons when i copy icon link to Notion

Environment: Mac(Mojave), Chrome browser

**Comment by tmmoond8** [comment]
thank you for your attention.
i justed check on my mac. but, i can see icons.
are you still can't see that?

**Comment by ChoiysApple** [comment]
I still cannot see icons
But when i try it on chrome secret mode, it works perfectly

**Comment by ChoiysApple** [comment]
This issue caused because of Ad block for Chrome. Thanks for your attention
